language: node_js
node_js:
- '5.10'
branches:
  only:
  - master
notifications:
  slack:
    secure: QA0RS3g/+8mLPBiE09y6MBMg0Qg3gLhK1Sn4yMNkAXTdcAhe9ITBGIkKXmH0JfJ5l8Zil0LE7jUighl33pJSdocA7Va6+TqkPxUn/MFZ1sE6lfPoSpcLznF/vNVTFDfaR3Gf3DF2Z5vN3LoIIZko5/OBVMrf/urU0i43qRtdv2u6vKdprpd23T1nrNtBL7oL9OUT+GDUCeMs3d0o3cp0OcQy3/RyTxOFzt9SWm0oGNTW8TPajiqsZ2f68fWUctXLW0F6Krday37W865FPdb4Mn+rSL6Js9z844cAXUmX96kybAD0o548D8IVNg7/zMSE1hdIz6Kw0l0ug3syBaCkEzR55F+CT1m5A3a2wzwd/epDfO6xnoTRZ1gcV6xNZzYeV//aOtRJGC4M+l4q2OvR/FReV7wjAcGML7r7jJpNZcCwBQARHJYF7TC3rNXBcoPNE+98tGFX3ehufi8rB6Q+6HdvuMu2KCIjLjIHMSR0S/PUKcffS26EY++XkjW74GjuUvLA6A3dzDrA8LXojYzdYf+mH/VbUVuwgXIbvscO1p3CEa3LDDYUDnPYRSS3tj+YNW/GAlJlOjk1roLWPiOOEczByDzxq6pz9uDDniu6w7Iriwg8MeHYmrRczAKx+fRYXoOPCmFz0YrR9WJCSqzQD1YRjiMylVEgij4j2ij42CI=
deploy:
  skip_cleanup: true
  provider: npm
  email: steffen@kolmer.net
  api_key:
    secure: WScNBXM/SkuKNLxUq7j5ymplC6SzqKqRC+dTt+13GckkrCiIEUxSLY2G5KaQlX54qLubeB7sngl4RufGRng2p0VHDumsPT2BFb1QIzuEouqI+sq/2621Y0bxKFkdjMLMa7n5qklRMP051/DOVOsuvT3Thx+qwH381W7BwSVZol30dcbbCovAFD4tYaacAn/TAhtBmqi1RLZQuoF+/tl2xyEtCrD/50Q+GShu+9WgYJHU3m/sDq4OgxYd2kbY2FUtHv3U1TTHf4ywzq6O+YoCTDNgpm6En/hmQACVhIvVTmOWOh8qNF307SpsT7W05zH+P2iNYJl8pIv/WNYKYdZ4Qvo2L6hNkzYceC1tNQxWTJyWP14TaFmzEmGRqIUqOlVSxB1g56lE582QDnoohUy5AjuY9mGxUQMk/3XrhrixoRWl9beG9+pr8UmZBkpvIUa2SHKyCM+D80TXjhAnNOAEL3PoLyD2Bbcsp3DRhB1u+oc7d3ZJ+YYy8RtKzqFnnSfga9ImT780YfYZAd+dx+O3w1azvWMubcb7d9jProS1CGsoAYGEbs1mCgsLHo2rhSj3kzap39Q6+AgWfh6zeAq8Gy5qXevMV3v3GBFnsm+54KRikn1zqNqHwAB7E9KXbjOHzKE0zSZHvFcBhzbP3eobMbuHfkLgvonM65vf3DZ1Rvo=
  on:
    tags: true
    repo: skolmer/babel-plugin-i18n-tag-translate